--- #YAML:1.0
name:                     Data-FormValidator-Constraints-Words
version:                  0.01
abstract:                 Data constraints for word inputs.
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  Test::More:             0.70

provides:
  Data::FormValidator::Constraints::Words:
    file:     lib/Data/FormValidator/Constraints/Words.pm
    version:  0.01
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-FormValidator-Constraints-Words

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
