--- #YAML:1.0
name:                     Data-FormValidator-Constraints-Words
version:                  0.05
abstract:                 Data constraints for word inputs.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

recommends:
  Data::FormValidator:    0
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
  Test::CPAN::Meta::JSON: 0.10
build_requires:
  Test::More:             0.70

provides:
  Data::FormValidator::Constraints::Words:
    file:     lib/Data/FormValidator/Constraints/Words.pm
    version:  0.05
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-FormValidator-Constraints-Words

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
